name: Merge-upstream

on:
  push:
    branches: 
      - dev
  schedule:
    - cron: '0 0 * * 1,3'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          # Upstream repository owner/name. For example, exions/merge-upstream
          upstream: telegramdesktop/tdesktop
          # Upstream branch to merge from. For example, master
          upstream-branch: dev
          # Branch to merge to. For example, master
          branch: dev
