name: Merge-upstream

on:
  push:
    branches: 
      - dev
  schedule:
    - cron: '0 0 * * 1,3'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Merge Upstream
      - run: | 
          git remote add -f upstream "https://github.com/telegramdesktop/tdesktop.git"
          git remote -v
          git branch --all
          git config --list
          git checkout dev
          git merge --ff-only upstream/dev 
          git push –allow-unrelated-histories
