name: Merge-upstream

on:
  push:
    branches: 
      - dev
  schedule:
    - cron: '0 0 * * 1,3'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: thiagokokada/merge-upstream@v1.0.2
        with:
          branch: dev
          # Recent GitHub changes needs a token with `workflow` permissions, so
          # the default GITHUB_TOKEN does not work anymore
          token: ${{ github.token }}
